# Generated by Django 3.2.3 on 2021-08-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.PositiveSmallIntegerField(choices=[(1, 'estudiante'), (2, 'encargadoFacultad'), (3, 'encargadoEscuela'), (4, 'admin')]),
        ),
        migrations.CreateModel(
            name='SolicitudUps',
            fields=[
                ('codigo_solicitud_ups', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('enlance', models.TextField(max_length=250)),
                ('observaciones', models.CharField(max_length=500)),
                ('estado_solicitud', models.TextField(default='En Proceso', max_length=50)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estudiante')),
            ],
        ),
    ]
