# Generated by Django 3.2.3 on 2021-07-09 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioSocial',
            fields=[
                ('codigo_servicio_social', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('cantidad_estudiantes', models.IntegerField()),
                ('cantidad_horas', models.IntegerField()),
                ('descripcion', models.CharField(max_length=250)),
                ('entidad', models.CharField(max_length=150)),
                ('propuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.propuesta')),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.solicitud')),
                ('tipo_servicio_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.tiposerviciosocial')),
            ],
        ),
    ]
