# Generated by Django 3.2.4 on 2021-09-03 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('codigo_docente', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nombres_docente', models.CharField(max_length=50)),
                ('apellidos_docente', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=15)),
                ('direccion_docente', models.CharField(max_length=250)),
                ('telefono_docente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('codigo_escuela', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_escuela', models.CharField(max_length=50)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='EncargadoFacultad',
            fields=[
                ('codigo_encargado', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField()),
                ('docente_encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.docente')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.facultad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncargadoEscuela',
            fields=[
                ('codigo_encargado', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('estado', models.BooleanField()),
                ('docente_encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.docente')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.escuela')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
