# Generated by Django 3.2.4 on 2021-07-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo_usuario',
            field=models.PositiveSmallIntegerField(choices=[(1, 'estudiante'), (2, 'encargadoFacultad'), (3, 'encargadoEscuela'), (4, 'admin')], default=4),
        ),
    ]
