# Generated by Django 3.2.3 on 2021-08-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210808_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudups',
            name='enlance',
            field=models.CharField(max_length=500),
        ),
    ]
