# Generated by Django 3.2.3 on 2021-09-09 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_docente_encargadoescuela_encargadofacultad_escuela'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('codigo_actividad', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=500)),
                ('encargado', models.CharField(max_length=50)),
                ('total_horas', models.IntegerField()),
                ('solicitud_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.solicitudserviciosocial')),
            ],
        ),
    ]
