# Generated by Django 3.2.3 on 2021-08-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_solicitudups_enlance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudups',
            old_name='enlance',
            new_name='enlace',
        ),
    ]
