# Generated by Django 3.2.3 on 2021-08-12 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_enlance_solicitudups_enlace'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicioSocial',
            fields=[
                ('codigo_solicitud_servicio', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estudiante')),
                ('servicio_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.serviciosocial')),
            ],
        ),
    ]
